let upgrades = {
	/*"template": {
		id: -69,
		name: "test",
		maxTier: 0,
		value: 0,
		tier: 0,
		cost: 0,
		points: 0,
		rarity: "test",
		sellValue: 0,
		effect(){return this.value},
		effectType: "test",
		description(){return `test`},
	},*/
	"point_bonus": {
		id: 0,
		name: "Headstart",
		maxTier: 8,
		value: 0,
		tier: 0,
		cost: 4,
		points: 1,
		rarity: "Common",
		sellValue: 0,
		effect(){return this.tier*20},
		effectType: "Starting Chips",
		description(){return `${this.effect()}+ Starting Chips`},
	},
	"rush_hour": {
		id: 1,
		name: "Rush Hour",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		effect(){return Math.floor(combo/10)},
		effectType: "Max Speed",
		description(){return `+1 Max Speed for every 10 Combo Held`},
	},
	"destatihud": {
		id: 2,
		name: "Destati Hud",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 4,
		points: 0,
		rarity: "Common",
		sellValue: 0,
		description(){return `Changes the look of the HUD`},
		unused: true
	},
	"treasured_memories": {
		id: 3,
		name: "Treasured Memories",
		maxTier: 5,
		value: 0,
		tier: 0,
		cost: 8,
		points: 1,
		rarity: "Rare",
		sellValue: 0,
		effect(){return this.tier*0.1},
		effectType: "Keep",
		description(){return `Keep ${this.effect()}% of Chips and Mult when you lose your Combo`},
	},
	"fork": {
		id: 4,
		name: "Fork",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 5,
		points: 2,
		rarity: "Common",
		sellValue: 0,
		effect(){return 1},
		effectType: "Lap Amount",
		description(){return `Gain +1 Available Laps when level begins`},
	},
	"cosmic_comet": {
		id: 5,
		name: "Cosmic Comet",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 10,
		points: 1,
		rarity: "Rare",
		sellValue: 0,
		effect(){return firstComboDrop?1:1.5},
		effectType: "Mult",
		description(){return `X1.50 Mult if your Combo has not been dropped`},
	},
	"promise_sword": {
		id: 6,
		name: "The Promise Sword",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 5,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		description(){return `Supertaunted enemies give guaranteed Critical Hits`},
	},
	"oldmach": {
		id: 7,
		name: "Old Mach Sounds",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 2,
		points: 0,
		rarity: "Common",
		sellValue: 0,
		description(){return `Changes the default mach sounds to the old mach sounds`},
	},
	"optimization": {
		id: 8,
		name: "Supercharge",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		effect(){return Math.floor(combo/10)*0.02},
		effectType: "Critical Chance",
		description(){return `+2% Critical Chance for every 10 Combo Held`},
	},
	"top_up": {
		id: 9,
		name: "Top-Up",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 3,
		points: 1,
		rarity: "Common",
		sellValue: 0,
		effect(){return Math.round(20-(availableTotal*0.3389830508474576))*0.03},
		effectType: "Combo Time",
		description(){return `Each unique Collectible Upgrade increases Combo Time by 3%`},
	},
	"red_team": {
		id: 10,
		name: "R.E.D.",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 5,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		effect(){return this.value},
		effectType: "Starting Mult",
		description(){return `Gains +1 Starting Mult for every Stupid Rat destroyed (Currently +${this.effect()}+ Starting Mult`},
	},
	"for_troubles": {
		id: 11,
		name: "For Your Troubles",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Common",
		sellValue: 0,
		description(){return `Collectible Upgrades give +5 Chips and +1 Mult when earned`},
	},
	"organic": {
		id: 12,
		name: "Organic Produce",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Common",
		sellValue: 0,
		description(){return `Toppins will give +100 Chips and +$2`},
	},
	"once_again": {
		id: 13,
		name: "Once More",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 10,
		points: 2,
		rarity: "Rare",
		sellValue: 0,
		description(){return `X1.25 Mult Boost when entering the Lap Portal`},
	},
	"abstract": {
		id: 14,
		name: "Hypothetical Upgrade",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 5,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		effect(){return totalSellValue/200},
		effectType: "Critical Chance",
		description(){return `Adds half the Sell Value of all Owned Upgrades to Critical Chance (Currently +${this.effect*100}% Critical Chance`},
	},
	"weirdroute": {
		id: 15,
		name: "SOUL",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 10,
		points: 2,
		rarity: "Rare",
		sellValue: 0,
		effect(){return combo>=75?2:1},
		effectType: "Mult",
		description(){return `Gives X2 Mult while Combo is above 75`},
	},
	"fragile": {
		id: 16,
		name: "Fragile",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 10,
		points: 1,
		rarity: "Rare",
		sellValue: 0,
		effect(){return damageTaken?1:2},
		effectType: "Mult",
		description(){return `Gives X2 Mult until you take damage`},
	},
	"goomba": {
		id: 17,
		name: "Goomba",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 7,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		description(){return `First killed enemy gives X1.50 Mult Boost`},
	},
	"sea_shells": {
		id: 18,
		name: "Sea Shells",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		effect(){return 0.05*Math.round(20-(availableTotal*0.3389830508474576))+1},
		effectType: "Mult",
		description(){return `Gives X1.05 Mult for each Collectible Upgrade`},
	},
	"burglar": {
		id: 19,
		name: "Duathlon",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 8,
		points: 2,
		rarity: "Uncommon",
		sellValue: 0,
		effect(){return 2},
		effectType: "Lap Amount",
		description(){return `Sets Critical Chance to 0%<br>Gain +2 Available Laps when levle begins`},
	},
	"gauntlet": {
		id: 20,
		name: "The Gauntlet",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 10,
		points: 1,
		rarity: "Rare",
		sellValue: 0,
		description(){return `Sell this Upgrade after killing ${gauntletLaps>=1?600:200} enemies [${this.value}] to gain +1 Available Lap`},
	},
	"reaver": {
		id: 21,
		name: "Dream Reaver Boomerang",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		effect(){return [-1, 0.2]},
		effectType: ["Lap Amount", "Critical Chance"],
		description(){return `-1 Available Laps<br>+20% Critical Chance`},
	},
	"party_crashers": {
		id: 22,
		name: "Party Crashers",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 4,
		points: 1,
		rarity: "Common",
		sellValue: 0,
		description(){return `Reduces Supertaunt Requirements in half`},
	},
	"fashionably_late": {
		id: 23,
		name: "Fashionably Late",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		description(){return `X1.50 Mult Boost when defeating Pillar John`},
	},
	"maniac": {
		id: 24,
		name: "Maniac",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 10,
		points: 2,
		rarity: "Rare",
		sellValue: 0,
		effect(){return (laps-tempLaps)*0.5+1},
		effectType: "Mult",
		description(){return `Gains X0.50 Mult for each Consecutive Lap (Currently X${this.effect(this.effect)})<br>(Resets at the end of level)`},
	},
	"snowball": {
		id: 25,
		name: "Snowballing",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 8,
		points: 2,
		rarity: "Rare",
		sellValue: 0,
		effect(){return combo/600},
		effectType: "Upgrade Chance",
		description(){return `Collectbile Upgrades are more common with a higher Combo`},
	},
	"engineer": {
		id: 26,
		name: "The Jag",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Common",
		sellValue: 0,
		description(){return `${Math.min(1**this.tier,4)} in 4 Chance to Tier Up a Random Owned Upgrade at the end of level<br>(Quantum Entanglement excluded)`},
	},
	"eggwuh": {
		id: 27,
		name: "It Come With Eggwuh",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 4,
		points: 1,
		rarity: "Common",
		sellValue: 0,
		description(){return `Gains $3 of Sell Value at the end of level`},
	},
	"ice_cream": {
		id: 28,
		name: "Ice Cream",
		maxTier: 1,
		value: 3,
		tier: 0,
		cost: 5,
		points: 1,
		rarity: "Common",
		sellValue: 0,
		description(){return `The first three enemies will drop a Collectible Upgrade and give +$1`},
	},
	"insane": {
		id: 29,
		name: "Going Insane",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 6,
		points: 1,
		rarity: "Uncommon",
		sellValue: 0,
		effect(){return firstComboDrop?0:0.25},
		effectType: "Keep",
		description(){return `Conserve 25% of Chips and Mult after dropping your First Combo`},
	},
	"vip": {
		id: 30,
		name: "VIP Pass",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 7,
		points: 2,
		rarity: "Uncommon",
		sellValue: 0,
		description(){return `Bypass any Locked Doors without requiring a Key`},
	},
	"stone": {
		id: 31,
		name: "Sturdy Guard",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 4,
		points: 1,
		rarity: "Common",
		effect(){return 0.5},
		effectType: "Combo Keep",
		description(){return `1 in 2 Chance for any damage taken to not reduce your Combo Time`},
	},
	"it": {
		id: 32,
		name: "X-iry",
		maxTier: 1,
		value: 0,
		tier: 0,
		cost: 77,
		points: 7,
		rarity: "Mythical",
		description(){return `Gains X1 Mult and X1 Chip for every Nth to the power of Combo (does nabsolutely othing)`},
	},
}

upgradeId = [
  "point_bonus",
  "rush_hour",
  "destatihud",
  "treasured_memories",
  "fork",
  "cosmic_comet",
  "promise_sword",
  "oldmach",
  "optimization",
  "top_up",
  "red_team",
  "for_troubles",
  "organic",
  "once_again",
  "abstract",
  "weirdroute",
  "fragile",
  "goomba",
  "sea_shells",
  "burglar",
  "gauntlet",
  "reaver",
  "party_crashers",
  "fashionably_late",
  "maniac",
  "snowball",
  "engineer",
  "eggwuh",
  "ice_cream",
  "insane",
  "vip",
  "stone",
  "it"
]

let miniUpgrades = {
	"knockback": {
		id: 0,
		name: "Knockback Reduction",
		maxTier: 8,
		tier: 0,
		rarity: "Common",
		effect(){return this.tier*0.1},
		description(){return `Reduces Knockback taken by ${this.effect()*100}%`},
	},
	"acceleration": {
		id: 1,
		name: "Pedal to the Metal",
		maxTier: 5,
		tier: 0,
		rarity: "Uncommon",
		effect(){return this.tier*0.4},
		description(){return `Increases Acceleration by ${this.effect()*100}%`},
	},
	"uppercut": {
		id: 2,
		name: "Rising Spiral",
		maxTier: 2,
		tier: 0,
		rarity: "Common",
		effect(){return this.tier*0.25},
		description(){return `Increases Uppercut Height by ${this.effect()*100}%`},
	},
	"electric": {
		id: 3,
		name: "Rubber Vest",
		maxTier: 1,
		tier: 0,
		rarity: "Uncommon",
		description(){return `Grants Immunity to all Electrical Damage Sources`},
	},
	"combo_time_fuel": {
		id: 4,
		name: "Combo Fuel",
		maxTier: 10,
		tier: 0,
		rarity: "Common",
		effect(){return this.tier*0.05},
		description(){return `Increases Combo Time by ${this.effect()*100}%`},
	},
	"jump": {
		id: 5,
		name: "Trampoline Shoes",
		maxTier: 2,
		tier: 0,
		rarity: "Common",
		effect(){return this.tier*0.25},
		description(){return `Increases Jump Height by ${this.effect()*100}%`},
	},
	"speed": {
		id: 6,
		name: "Runner",
		maxTier: 9,
		tier: 0,
		rarity: "Common",
		effect(){return this.tier*2},
		description(){return `Increases Max Speed by ${this.effect()}`},
	},
	"magnet": {
		id: 7,
		name: "Magnetar",
		maxTier: 10,
		tier: 0,
		rarity: "Common",
		description(){return `Increases the pickup range of earning Collectibles`},
	},
	"nja_jump": {
		id: 8,
		name: "NJA: S-Jump Conservation",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Conserves all prior horizontal speed when exiting a superjump`},
	},
	"nja_fastjump": {
		id: 9,
		name: "NJA: Fast Superjumps",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Superjumps are 33% faster<br>Superjump Cancels are 3x as fast<br>You can Superjump instantly`},
	},
	"nja_betterwallgrab": {
		id: 10,
		name: "NJA: Wallgrab Conservation",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Converts all Horizontal Speed to Vertical Speed when Grabbing into a Wall`},
	},
	"nja_betterwalljump": {
		id: 11,
		name: "NJA: Better Walljumps",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Conserves all Speed when Walljumping`},
	},
	"nja_fastdive": {
		id: 12,
		name: "NJA: Fast Diving",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Converts all Horizontal Speed to your Diving Speed`},
	},
	"nja_fastbreak": {
		id: 13,
		name: "NJA: Fast Braking",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Slow down faster when skidding from a Mach Run`},
	},
	"nja_cutscene": {
		id: 14,
		name: "NJA: Skip Cutscenes",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Most Object Cutscenes and Pauses will be Skipped`},
	},
	"nja_pizzabox": {
		id: 15,
		name: "NJA: Pizzabox Groundpound",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Groundpound out of Pizzaboxes instead of Free Falling`},
	},
	"nja_drift": {
		id: 16,
		name: "NJA: Drifting Conservation",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Conserves all Speed when Turning in a Mach Run`},
	},
	"nja_superwalk": {
		id: 17,
		name: "NJA: Superjump Walking",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Walk Faster while Charging a Superjump`},
	},
	"nja_terminal": {
		id: 18,
		name: "NJA: No Terminal Velocity",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Maximum Falling Speed won't be Limited`},
	},
	"nja_quickdrift": {
		id: 19,
		name: "NJA: Quick Drifting",
		maxTier: 1,
		tier: 0,
		rarity: "NJA",
		description(){return `Turn around while Mach Running faster`},
	},
}